// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlupmxywmfmxgpeksmxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsdXBteHl3bWZteGdwZWtzbXhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyOTA2MzgsImV4cCI6MjA2NTg2NjYzOH0.imtHWbupsE4gyl7fNeIoNIpYb7eDtxXJV4pJ9oHj87k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);